### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by grissius** [AckeeCZ/cosmas#14]
Using cosmas reports `MaxListenersExceededWarning` in Jest tests. Probably related to pino's pretty.
```
(node:28435) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:243:17)
    at WriteStream.addListener (events.js:259:10)
    at WriteStream.Readable.on (_stream_readable.js:799:35)
    at WriteStream.once (events.js:290:8)
    at DestroyableTransform.Object.<anonymous>.Readable.pipe (/home/smolijar/Projects/my-project/node_modules/readable-stream/lib/_stream_readable.js:657:8)
    at DestroyableTransform.stream.pipe (/home/smolijar/Projects/my-project/node_modules/pino/pretty.js:154:17)
    at defaultLogger (/home/smolijar/Projects/my-project/node_modules/cosmas/src/index.ts:71:15)
    at Object.loggerFactory (/home/smolijar/Projects/my-project/node_modules/cosmas/src/index.ts:155:22)
    at Object.<anonymous> (/home/smolijar/Projects/my-project/src/app/logger.ts:4:22)
    at Runtime._execModule (/home/smolijar/Projects/my-project/node_modules/jest-runtime/build/index.js:858:13)
```

Something in [defaultLogger](https://github.com/AckeeCZ/cosmas/blob/master/src/index.ts#L52), not sure what, maps don't seem to be working well.

Turning pretty on/off doesn't change the behavior.

*Edit* This has been [reported](https://github.com/pinojs/pino/issues/431) when dynamically spawning loggers

**Comment by grissius** [comment]
Omg. This is caused by Jest disabling the module cache. Logger instantiates for each  case. I will consider setting `process.setMaxListeners(0);` for the tests. Sorry.
